# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Baryo < Formula
  desc "A local AI chat CLI powered by Docker Model Runner"
  homepage "https://github.com/BaryoDev/Baryo.CLI"
  version "0.2.0"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/BaryoDev/Baryo.CLI/releases/download/v0.2.0/baryo_0.2.0_darwin_amd64.tar.gz"
      sha256 "ee56c0602f0f3ee8e63697d63eeaccf6e20d6dd1aa10f3013ddb94c75c5d879f"

      define_method(:install) do
        bin.install "baryo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/BaryoDev/Baryo.CLI/releases/download/v0.2.0/baryo_0.2.0_darwin_arm64.tar.gz"
      sha256 "4bbfb50a145ef676bae605bdb80ba1a05b91225d27c8d3a5b3bc944ea7303afa"

      define_method(:install) do
        bin.install "baryo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/BaryoDev/Baryo.CLI/releases/download/v0.2.0/baryo_0.2.0_linux_amd64.tar.gz"
      sha256 "faea0585b4dad1b7cc5d5607c3c79cc9707af5985e30bb8d245ef0b81dff31c9"
      define_method(:install) do
        bin.install "baryo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BaryoDev/Baryo.CLI/releases/download/v0.2.0/baryo_0.2.0_linux_arm64.tar.gz"
      sha256 "b56d42c57d2e80b68f49355cc959385ce1bf7f31472e551d4305fe4db8ff05bc"
      define_method(:install) do
        bin.install "baryo"
      end
    end
  end

  test do
    assert_match "baryo version", shell_output("#{bin}/baryo --version")
  end
end
