# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Baryo < Formula
  desc "A local AI chat CLI powered by Docker Model Runner"
  homepage "https://github.com/BaryoDev/Baryo.CLI"
  version "0.6.0"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/BaryoDev/Baryo.CLI/releases/download/v0.6.0/baryo_0.6.0_darwin_amd64.tar.gz"
      sha256 "0f366ce258be812c78c90f11b20da470a94e7ac3df926f42a3e4f467cb519f93"

      define_method(:install) do
        bin.install "baryo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/BaryoDev/Baryo.CLI/releases/download/v0.6.0/baryo_0.6.0_darwin_arm64.tar.gz"
      sha256 "0171b4852294b746a280cada7371042312389dd47c191ed5f6ff4cf32e2ef384"

      define_method(:install) do
        bin.install "baryo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/BaryoDev/Baryo.CLI/releases/download/v0.6.0/baryo_0.6.0_linux_amd64.tar.gz"
      sha256 "95aa24cdcdc2722bc3567d8cddba7dd984f05d86c1f508ffc07d498584a5de17"
      define_method(:install) do
        bin.install "baryo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BaryoDev/Baryo.CLI/releases/download/v0.6.0/baryo_0.6.0_linux_arm64.tar.gz"
      sha256 "448aec908062e5f1c3b7303f26710909f1d323662cdb643bff8777cfc5640aa7"
      define_method(:install) do
        bin.install "baryo"
      end
    end
  end

  test do
    assert_match "baryo version", shell_output("#{bin}/baryo --version")
  end
end
